POST http://localhost:8080/logIn
Content-Type: application/json

{
  "login" : "admin",
  "password" : "admin"
}

###

GET http://localhost:8080/users
Authorization:

###

POST http://localhost:8080/logIn
Content-Type: application/json

{
  "login" : "azyam",
  "password" : "aze"
}

###

GET http://localhost:8080/users
Authorization:

###

POST http://localhost:8080/signUp

login: teddy
email: ted@gmail.com
password: bear11